import { Product } from "@/types";

// Суреттер жолын генерациялайтын helper
// imgs(1, 3) → ["/products/1/1.jpg", "/products/1/2.jpg", "/products/1/3.jpg"]
// Суреттер жоқ болса imgs(id, 0) → [] — emoji көрінеді
function imgs(id: number, count: number): string[] {
  return Array.from({ length: count }, (_, i) => `/products/${id}/${i + 1}.jpg`);
}

export const PRODUCTS: Product[] = [
  {
    id: 1,
    nameKz: "Біл Бала",
    nameRu: "Бил Бала",
    descKz: "Интерактивті оқыту кітабы — балалар үшін қызықты тапсырмалар мен ойындар.",
    descRu: "Интерактивная обучающая книга с заданиями и играми для детей.",
    price: 9990,
    age: "3+",
    cat: "book",
    hit: true,
    emoji: "📚",
    images: imgs(1, 5),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 2,
    nameKz: "Бал әуен",
    nameRu: "Бал Ауен",
    descKz: "Қазақша пластинка ойнатқыш — балаларға арналған музыкалық ойыншық.",
    descRu: "Казахский проигрыватель пластинок — музыкальная игрушка для детей.",
    price: 14900,
    age: "2+",
    cat: "game",
    hit: true,
    emoji: "🎵",
    images: imgs(2, 4),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 3,
    nameKz: "Сөйлеп үйрен",
    nameRu: "Сейлеп үйрен",
    descKz: "Логопедиялық карточкалар жиынтығы — дыбыстарды дұрыс айтуға үйретеді.",
    descRu: "Логопедические карточки для правильного произношения звуков.",
    price: 8970,
    age: "2+",
    cat: "book",
    hit: true,
    emoji: "🗣️",
    images: imgs(3, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 4,
    nameKz: "Білімге Қадам",
    nameRu: "Білімге Қадам",
    descKz: "Мектепке дейінгі дамыту жинағы — есеп, жазу, оқу негіздері.",
    descRu: "Дошкольный развивающий набор — счёт, письмо, чтение.",
    price: 8000,
    age: "3+",
    cat: "book",
    hit: false,
    emoji: "📖",
    images: imgs(4, 3),
    rating: 5.0,
    isNew: true,
  },
  {
    id: 5,
    nameKz: "Қош бол ана сүті",
    nameRu: "Қош бол ана сүті",
    descKz: "Интерактивті аудио кітап — нәрестелерге арналған бірінші кітап.",
    descRu: "Интерактивная аудиокнига для самых маленьких.",
    price: 4990,
    age: "0+",
    cat: "book",
    hit: false,
    emoji: "📕",
    images: imgs(5, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 6,
    nameKz: "100 000 не үшін?",
    nameRu: "100 000 не үшін?",
    descKz: "Дыбысты интерактивті энциклопедия — балаларды ойлауға үйретеді.",
    descRu: "Звуковая энциклопедия, развивающая мышление детей.",
    price: 9490,
    age: "4+",
    cat: "book",
    hit: false,
    emoji: "🔍",
    images: imgs(6, 2),
    rating: 5.0,
    isNew: true,
  },
  {
    id: 7,
    nameKz: "Ордаген",
    nameRu: "Ордаген",
    descKz: "Интерактивті ертегілер комикс форматында — қазақ фольклоры.",
    descRu: "Интерактивные сказки в формате комикса — казахский фольклор.",
    price: 2990,
    age: "4+",
    cat: "book",
    hit: false,
    emoji: "📓",
    images: imgs(7, 2),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 8,
    nameKz: "Карта Табата",
    nameRu: "Карта Табата",
    descKz: "Математикалық дамытушы ойын — санауды ойнай отырып үйренеді.",
    descRu: "Математическая развивающая игра — учимся считать играя.",
    price: 6500,
    age: "6+",
    cat: "game",
    hit: false,
    emoji: "🔢",
    images: imgs(8, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 9,
    nameKz: "Саусақ әліпби",
    nameRu: "Саусақ әліпби",
    descKz: "Интерактивті дамытушы құрал — саусақ моторикасын дамытады.",
    descRu: "Интерактивное развивающее пособие для мелкой моторики.",
    price: 2990,
    age: "2+",
    cat: "game",
    hit: false,
    emoji: "✋",
    images: imgs(9, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 10,
    nameKz: "Білім картасы",
    nameRu: "Білім картасы",
    descKz: "Сөйлейтін робот Тілашар — қазақша сөйлеуге үйретеді.",
    descRu: "Говорящий робот — обучает казахскому языку в игровой форме.",
    price: 8990,
    age: "6+",
    cat: "game",
    hit: true,
    emoji: "🤖",
    images: imgs(10, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 11,
    nameKz: "Дино кард",
    nameRu: "Дино кард",
    descKz: "Қазақша тіл ашар карточкалар — сөздікті кеңейтуге арналған.",
    descRu: "Казахские карточки для развития речи и расширения словаря.",
    price: 3590,
    age: "2+",
    cat: "game",
    hit: false,
    emoji: "🦕",
    images: imgs(11, 4),
    rating: 5.0,
    isNew: true,
  },
  {
    id: 12,
    nameKz: "Сөйлейтін әліппе",
    nameRu: "Сөйлейтін әліппе",
    descKz: "Қазақ әліпбиінің аудио плакаты — дыбыстарды естіп үйренеді.",
    descRu: "Аудио плакат казахского алфавита — учим буквы на слух.",
    price: 3990,
    age: "3+",
    cat: "poster",
    hit: true,
    emoji: "🔤",
    images: imgs(12, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 13,
    nameKz: "Ағылшын әліппе",
    nameRu: "Ағылшын әліппе",
    descKz: "Ағылшын тілінің аудио плакаты — English алфавитін үйренеміз.",
    descRu: "Аудио плакат английского алфавита — учим English буквы.",
    price: 1990,
    age: "2+",
    cat: "poster",
    hit: false,
    emoji: "🇬🇧",
    images: imgs(13, 2),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 14,
    nameKz: "Ауыл жануарлары",
    nameRu: "Ауыл жануарлары",
    descKz: "Жануарлардың аудио плакаты — үй жануарларын қазақша үйренеміз.",
    descRu: "Аудиоплакат — учим домашних животных на казахском.",
    price: 3990,
    age: "2+",
    cat: "poster",
    hit: false,
    emoji: "🐄",
    images: imgs(14, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 15,
    nameKz: "Әлем картасы",
    nameRu: "Әлем картасы",
    descKz: "Интерактивті оқыту плакаты — елдер мен континенттерді үйренеміз.",
    descRu: "Интерактивный обучающий плакат — страны и континенты.",
    price: 4590,
    age: "3+",
    cat: "game",
    hit: false,
    emoji: "🌍",
    images: imgs(15, 2),
    rating: 5.0,
    isNew: true,
  },
  {
    id: 16,
    nameKz: "Қазақстан картасы",
    nameRu: "Қазақстан картасы",
    descKz: "Интерактивті магнитті пазл-карта — Қазақстан облыстарын үйренеміз.",
    descRu: "Интерактивная магнитная пазл-карта Казахстана.",
    price: 2500,
    age: "3+",
    cat: "game",
    hit: false,
    emoji: "🗺️",
    images: imgs(16, 3),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 17,
    nameKz: "Ақылды робот",
    nameRu: "Ақылды робот",
    descKz: "Сөйлейтін робот қашықтан басқарумен — ең заманауи ойыншық.",
    descRu: "Говорящий робот на радиоуправлении — самая современная игрушка.",
    price: 12750,
    age: "6+",
    cat: "game",
    hit: true,
    emoji: "🦾",
    images: imgs(17, 2),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 18,
    nameKz: "Жазу әліппесі",
    nameRu: "Жазу әліппесі",
    descKz: "Интерактивті жазу дамыту құралы — дұрыс жазуды үйренеміз.",
    descRu: "Интерактивное развитие письма — учимся правильно писать.",
    price: 2000,
    age: "3+",
    cat: "book",
    hit: false,
    emoji: "✏️",
    images: imgs(18, 2),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 19,
    nameKz: "Сиқырлы дәптер",
    nameRu: "Сиқырлы дәптер",
    descKz: "Мектепке дайындық жинағы — бірінші сыныпқа дайын боласыз.",
    descRu: "Набор для подготовки к школе — будем готовы к 1 классу.",
    price: 1200,
    age: "3+",
    cat: "book",
    hit: false,
    emoji: "📝",
    images: imgs(19, 4),
    rating: 5.0,
    isNew: false,
  },
  {
    id: 20,
    nameKz: "Бастырмақ",
    nameRu: "Бастырмақ",
    descKz: "Интерактивті дыбыстық дамыту құралы — нәрестелерге арналған.",
    descRu: "Интерактивное звуковое развитие для малышей.",
    price: 1990,
    age: "1+",
    cat: "game",
    hit: false,
    emoji: "🔊",
    images: imgs(20, 3),
    rating: 5.0,
    isNew: false,
  },
];

export function getProductById(id: number): Product | undefined {
  return PRODUCTS.find((p) => p.id === id);
}

export const MAX_PRICE = Math.max(...PRODUCTS.map((p) => p.price));
export const MIN_PRICE = Math.min(...PRODUCTS.map((p) => p.price));
